import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { AnimatePresence, motion } from 'framer-motion';
import { Check, Clipboard, Download, FileText, Loader2, Mail, Printer, Share2 } from 'lucide-react';
import { cn } from '@paladian/ui';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { DnaGlyph } from '@/components/DnaGlyph';
import { useConfigStore } from '@/store/configStore';
import { useLangStore, tr } from '@/store/langStore';

type GenState = 'idle' | 'generating' | 'ready';

const PDF_FILENAME = `Kopanica-Beravci-Thesis-${new Date().toISOString().slice(0, 10)}.pdf`;

/** Markdown version of the thesis for "Copy as Markdown" export. */
function buildMarkdown(cfg: { capacityMW: number; tracking: string; underPanel: string }): string {
  return `# Kopanica-Beravci Agrivoltaic Zone · Investment Thesis

**HR-AGRI-2026-KOPANICA-01** · Paladina Investments · ${new Date().toISOString().slice(0, 10)}

80.3 ha · Općina Velika Kopanica · Brodsko-Posavska županija · 45.1348°N 18.4130°E
${cfg.capacityMW} MW · ${cfg.tracking} tracking · ${cfg.underPanel} under-panel

---

## Macro thesis

Net metering ended **2026-01-01**. Household rooftop IRR collapsed from 18% → 8%. Utility-scale + agrivoltaic became the only serious Croatian solar segment. OIEH estimates 2,500 MW of free grid capacity across Slavonia · Banovina · Istria — a window industry observers expect to close within 28 months.

> "You are not building a solar farm. You are warehousing grid rights and subsidy eligibility for a 25-year window that closes in 2028."

## Key figures · 30 MW base case

| Metric | Value |
|---|---|
| CAPEX | €21.0M |
| Payback | 7.4 yr |
| NPV (25 yr) | €30.4M |
| Equity IRR | 11.4% |
| DSCR · Y1 | 1.78× |
| Exit EV · Y10 | €30.4M @ 6.5% cap |

## Funding stack · non-dilutive (75% of CAPEX · €15.8M)

- FZOEU OI-2026-03 — €4.2M (T−88d)
- NPOO C1.2.R1-I1 — €8.4M (T−165d)
- HBOR Zeleni kredit — €3.2M

## Why Kopanica-Beravci wins

- A3 motorway exit 0.3 km · D7 direct border · MP13C railway 0.7 km · Sava 2.5 km
- HV line + gas pipeline already on site
- HOPS queue #14 · connection agreement Q3 2027
- Phase 2 optionality on 80.3 ha — unlocks +40 MW when substation upgrades

---

*Generated by Panonica · Pannonian Solar Intelligence · live deal room linked.*
`;
}

export function ThesisRoute() {
  const [state, setState] = useState<GenState>('idle');
  const [toast, setToast] = useState<string | null>(null);
  const [pdfBlob, setPdfBlob] = useState<Blob | null>(null);
  const articleRef = useRef<HTMLDivElement>(null);
  const config = useConfigStore();
  const lang = useLangStore((s) => s.lang);

  const handleGenerate = async () => {
    if (state !== 'idle' || !articleRef.current) return;
    setState('generating');

    // Give the compile animation 900ms to breathe before we snapshot
    await new Promise((r) => setTimeout(r, 900));

    try {
      const canvas = await html2canvas(articleRef.current, {
        backgroundColor: '#fafaf7',
        scale: 2,
        useCORS: true,
        logging: false,
      });

      const imgWidthMm = 210; // A4 width
      const pageHeightMm = 297;
      const imgHeightMm = (canvas.height * imgWidthMm) / canvas.width;

      const pdf = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' });
      const imgData = canvas.toDataURL('image/jpeg', 0.92);

      let heightLeft = imgHeightMm;
      let position = 0;
      let pageIdx = 0;

      while (heightLeft > 0) {
        if (pageIdx > 0) pdf.addPage();
        pdf.addImage(imgData, 'JPEG', 0, -position, imgWidthMm, imgHeightMm, undefined, 'FAST');
        heightLeft -= pageHeightMm;
        position += pageHeightMm;
        pageIdx += 1;
        if (pageIdx > 6) break; // safety
      }

      // PDF metadata
      pdf.setProperties({
        title: 'Kopanica-Beravci Agrivoltaic Zone · Investment Thesis',
        author: 'Panonica · Paladina Investments',
        subject: '30 MW Agrivoltaic · 80.3 ha · Velika Kopanica',
        keywords: 'agrivoltaic, solar, Croatia, Paladina, Kopanica-Beravci, FZOEU, NPOO',
        creator: 'Panonica v0.1.0',
      });

      const blob = pdf.output('blob');
      setPdfBlob(blob);
      setState('ready');
      setToast(`${pageIdx}-page PDF ready · ${(blob.size / 1024).toFixed(0)} kB`);
      setTimeout(() => setToast(null), 3200);
    } catch (err) {
      console.error('[thesis-pdf]', err);
      setState('idle');
      setToast('PDF generation failed · check console');
      setTimeout(() => setToast(null), 3000);
    }
  };

  const handleDownload = () => {
    if (!pdfBlob) return;
    const url = URL.createObjectURL(pdfBlob);
    const a = document.createElement('a');
    a.href = url;
    a.download = PDF_FILENAME;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setToast(`Downloaded · ${PDF_FILENAME}`);
    setTimeout(() => setToast(null), 2600);
  };

  const handleCopyMarkdown = async () => {
    const md = buildMarkdown({
      capacityMW: config.capacityMW,
      tracking: config.tracking,
      underPanel: config.underPanel,
    });
    try {
      await navigator.clipboard.writeText(md);
      setToast('Markdown copied · paste into any doc');
    } catch {
      setToast('Clipboard blocked · open devtools to copy');
    }
    setTimeout(() => setToast(null), 2600);
  };

  const handleEmailIvan = () => {
    const subject = encodeURIComponent('Kopanica-Beravci · Investment Thesis · live link attached');
    const body = encodeURIComponent(
      `Ivane,

Attaching the Kopanica-Beravci investment thesis we walked through.

Base case (30 MW Phase 1, Agri-PV + Sheep):
  · CAPEX  €21.0M
  · IRR    11.4% equity · 1.78× DSCR Y1
  · NPV    €30.4M (25-yr · 8% discount)
  · Payback 7.4 years
  · Exit EV ~€30M at 6.5% cap in Y10

The live deal room stays synced with the latest model state —
open on phone or desktop to explore any section interactively.
I'll generate the shareable URL via the app's deal-room module and
send separately.

Tomo · Panonica
`,
    );
    window.open(`mailto:ivan@paladina.hr?subject=${subject}&body=${body}`);
    setToast('Email draft opened in your mail client');
    setTimeout(() => setToast(null), 2600);
  };

  const handleShareDealRoom = () => {
    window.dispatchEvent(new CustomEvent('panonica:deal-room-generate'));
  };

  // Global trigger (from Command Palette)
  useEffect(() => {
    const h = () => handleGenerate();
    window.addEventListener('panonica:thesis-generate', h);
    return () => window.removeEventListener('panonica:thesis-generate', h);
  }, [state]);

  return (
    <section className="relative flex min-h-full gap-8 px-12 py-10">
      {/* CENTER — document */}
      <div className="flex flex-1 flex-col items-center justify-start gap-6">
        {/* Toolbar */}
        <div className="flex items-center gap-4">
          <button
            onClick={handleGenerate}
            disabled={state !== 'idle'}
            className={cn(
              'inline-flex items-center gap-2.5 rounded-md border px-4 py-2.5 font-mono text-[11px] uppercase tracking-[0.22em] transition-all',
              state === 'idle' &&
                'border-pulse/40 bg-pulse/10 text-pulse hover:shadow-glow-pulse',
              state === 'generating' && 'border-border bg-surface text-text-muted',
              state === 'ready' && 'border-agri/40 bg-agri/10 text-agri',
            )}
          >
            {state === 'idle' && (
              <>
                <FileText className="h-3.5 w-3.5" strokeWidth={2} /> generate pdf
              </>
            )}
            {state === 'generating' && (
              <>
                <Loader2 className="h-3.5 w-3.5 animate-spin" strokeWidth={2} /> compiling thesis
              </>
            )}
            {state === 'ready' && (
              <>
                <Check className="h-3.5 w-3.5" strokeWidth={2.5} /> ready
              </>
            )}
          </button>

          <AnimatePresence>
            {state === 'ready' && (
              <motion.button
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.4 }}
                onClick={handleDownload}
                className="inline-flex items-center gap-2 rounded-md border border-agri/40 bg-agri/10 px-4 py-2.5 font-mono text-[11px] uppercase tracking-[0.22em] text-agri transition-all hover:bg-agri/20 hover:shadow-glow-pulse"
              >
                <Download className="h-3.5 w-3.5" strokeWidth={1.8} /> download PDF
              </motion.button>
            )}
          </AnimatePresence>

          {/* Divider */}
          <div className="h-6 w-px bg-border" />

          {/* Markdown export */}
          <button
            onClick={handleCopyMarkdown}
            className="inline-flex items-center gap-2 rounded-md border border-border-bright bg-surface/60 px-3 py-2.5 font-mono text-[11px] uppercase tracking-[0.22em] text-text-secondary transition-colors hover:border-pulse hover:text-pulse"
            title="Copy a text-only Markdown version to clipboard"
          >
            <Clipboard className="h-3.5 w-3.5" strokeWidth={1.8} /> copy markdown
          </button>

          {/* Email to Ivan */}
          <button
            onClick={handleEmailIvan}
            className="inline-flex items-center gap-2 rounded-md border border-border-bright bg-surface/60 px-3 py-2.5 font-mono text-[11px] uppercase tracking-[0.22em] text-text-secondary transition-colors hover:border-sun hover:text-sun"
            title="Open a pre-filled email draft to Ivan Paladina"
          >
            <Mail className="h-3.5 w-3.5" strokeWidth={1.8} /> email ivan
          </button>

          {/* Generate deal room link */}
          <button
            onClick={handleShareDealRoom}
            className="inline-flex items-center gap-2 rounded-md border border-border-bright bg-surface/60 px-3 py-2.5 font-mono text-[11px] uppercase tracking-[0.22em] text-text-secondary transition-colors hover:border-agri hover:text-agri"
            title="Generate a QR-coded shareable Deal Room URL"
          >
            <Share2 className="h-3.5 w-3.5" strokeWidth={1.8} /> share · deal room
          </button>

          {/* One-pager quick-jump */}
          <Link
            to="/one-pager"
            className="inline-flex items-center gap-2 rounded-md border border-border-bright bg-surface/60 px-3 py-2.5 font-mono text-[11px] uppercase tracking-[0.22em] text-text-secondary transition-colors hover:border-pulse hover:text-pulse"
            title="Open the single-page A4 leave-behind"
          >
            <Printer className="h-3.5 w-3.5" strokeWidth={1.8} /> one-pager
          </Link>
        </div>

        {/* The document */}
        <div className="relative">
          {/* Compile flash overlay */}
          <AnimatePresence>
            {state === 'generating' && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="pointer-events-none absolute inset-0 z-10 overflow-hidden rounded-sm"
              >
                {[...Array(4)].map((_, i) => (
                  <motion.div
                    key={i}
                    className="absolute left-0 right-0 h-[1px] bg-pulse/80"
                    initial={{ y: 0 }}
                    animate={{ y: ['0%', '100%'] }}
                    transition={{
                      duration: 0.8,
                      repeat: Infinity,
                      delay: i * 0.2,
                      ease: 'linear',
                    }}
                    style={{ boxShadow: '0 0 12px rgb(124 92 255 / 0.6)' }}
                  />
                ))}
              </motion.div>
            )}
          </AnimatePresence>

          <motion.article
            ref={articleRef}
            animate={{
              scale: state === 'generating' ? 0.995 : 1,
              filter: state === 'generating' ? 'brightness(1.05)' : 'none',
            }}
            className="relative w-[680px] min-h-[880px] rounded-sm bg-[#fafaf7] text-[#0f0f10] shadow-2xl"
            style={{
              boxShadow:
                '0 32px 60px -20px rgba(124,92,255,0.15), 0 20px 40px -10px rgba(0,0,0,0.5)',
            }}
          >
            {/* Cover */}
            <div className="flex flex-col gap-6 p-14">
              <div className="flex items-baseline justify-between border-b border-black/10 pb-4">
                <span className="font-mono text-[10px] uppercase tracking-[0.28em] text-black/60">
                  {tr('panonica // investment thesis', 'panonica // investicijska teza', lang)}
                </span>
                <span className="font-mono text-[10px] text-black/60">HR-AGRI-2026-KOPANICA-01</span>
              </div>

              <div className="py-10">
                <h1 className="font-display text-[3.2rem] uppercase leading-[0.95] tracking-tech-tight">
                  Kopanica-Beravci
                  <br />
                  {tr('Agrivoltaic Zone', 'Agrivoltažna Zona', lang)}
                </h1>
                <p className="mt-2 font-mono text-xs uppercase tracking-[0.2em] text-black/60">
                  80.3 HA · OPĆINA VELIKA KOPANICA · 30 MW AGV
                </p>
                <p className="mt-4 max-w-md font-serif text-base italic leading-snug text-black/80">
                  A first-mover agrivoltaic position in Pannonian Croatia, timed to the
                  2026-01-01 regulatory inflection point. Ribić Breg precedent (60 ha · 30 MW ·
                  Solida d.o.o.) scaled to 80.3 ha produces a €30M year-10 exit — warehoused grid
                  rights + subsidy eligibility on a 25-year tail.
                </p>
              </div>

              <div className="grid grid-cols-2 gap-6 border-t border-black/10 pt-6">
                <FieldDark label="Owner" value="Paladina Investments" />
                <FieldDark label="Date" value="April 2026" />
                <FieldDark label="Proposed" value="Agri-PV + Sheep (30 MW)" />
                <FieldDark label="Confidence" value="HIGH" tone="pulse" />
              </div>

              <div className="mt-6 flex items-end justify-between border-t border-black/10 pt-6">
                <div>
                  <div className="font-mono text-[9px] uppercase tracking-[0.24em] text-black/50">
                    analyzed by
                  </div>
                  <div className="font-display text-xl tracking-tech-tight">panonica_</div>
                  <div className="mt-1 font-mono text-[9px] uppercase tracking-[0.22em] text-black/50">
                    deal DNA · {config.capacityMW}MW · {config.tracking} · {config.underPanel}
                  </div>
                </div>
                <div className="flex items-end gap-3">
                  <DnaGlyph config={config} size={92} paper />
                  <QrBlock />
                </div>
              </div>
            </div>

            {/* Page 2 — Macro thesis */}
            <div className="border-t-2 border-dashed border-black/10 px-14 py-10">
              <h2 className="mb-2 font-display text-xl uppercase tracking-tech-tight">
                Macro thesis
              </h2>
              <p className="font-serif text-sm leading-relaxed text-black/80">
                Net metering ended <strong>2026-01-01</strong>. Household rooftop IRR collapsed
                from 18% → 8%. Utility-scale + agrivoltaic became the only serious Croatian solar
                segment. OIEH estimates 2,500 MW of free grid capacity across Slavonia /
                Banovina / Istria — a window industry observers expect to close within 28 months.
              </p>
              <div className="mt-4 grid grid-cols-3 gap-3 border-y border-black/10 py-4">
                <InlineStat k="Slavonia free MW" v="1,180" />
                <InlineStat k="Queue position" v="#14 / 62" />
                <InlineStat k="Ribić Breg comp" v="30 MW · €21M" />
              </div>
              <p className="mt-4 font-serif text-sm italic leading-relaxed text-black/70">
                &ldquo;You are not building a solar farm. You are warehousing grid rights and
                subsidy eligibility for a 25-year window that closes in 2028.&rdquo;
              </p>
            </div>

            {/* Page 3 — Key figures */}
            <div className="border-t-2 border-dashed border-black/10 px-14 py-10">
              <h2 className="mb-2 font-display text-xl uppercase tracking-tech-tight">
                Key figures · 30 MW base case
              </h2>
              <div className="grid grid-cols-4 gap-4 border-b border-black/10 pb-6">
                <BigStat label="CAPEX" value="€21.0M" />
                <BigStat label="PAYBACK" value="7.4 yr" />
                <BigStat label="NPV (25)" value="€30.4M" />
                <BigStat label="IRR" value="11.4%" />
              </div>

              <div className="mt-6 grid grid-cols-2 gap-6">
                <div>
                  <div className="mb-1 font-mono text-[9px] uppercase tracking-[0.24em] text-black/50">
                    funding stack · non-dilutive
                  </div>
                  <div className="flex items-end gap-2">
                    <div className="font-display text-3xl tracking-tech-tight">€15.8M</div>
                    <div className="pb-1 font-mono text-[10px] uppercase text-black/50">
                      75% of CAPEX
                    </div>
                  </div>
                  <ul className="mt-3 space-y-1 font-serif text-sm text-black/80">
                    <li>• FZOEU OI-2026-03 — €4.2M (T−88d)</li>
                    <li>• NPOO C1.2.R1-I1 — €8.4M (T−165d)</li>
                    <li>• HBOR Zeleni kredit — €3.2M</li>
                  </ul>
                </div>

                <div>
                  <div className="mb-1 font-mono text-[9px] uppercase tracking-[0.24em] text-black/50">
                    exit scenario · year 10
                  </div>
                  <div className="flex items-end gap-2">
                    <div className="font-display text-3xl tracking-tech-tight">€30.4M</div>
                    <div className="pb-1 font-mono text-[10px] uppercase text-black/50">
                      EV · 6.5% cap
                    </div>
                  </div>
                  <ul className="mt-3 space-y-1 font-serif text-sm text-black/80">
                    <li>• Y10 stabilized EBITDA · €2.82M</li>
                    <li>• Equity MoM · 7.8× (€5.3M → €40.8M)</li>
                    <li>• 9.5× Kupari 10% paper value</li>
                  </ul>
                </div>
              </div>
            </div>

            {/* Page 4 — Intelligence */}
            <div className="border-t-2 border-dashed border-black/10 px-14 py-10">
              <h2 className="mb-2 font-display text-xl uppercase tracking-tech-tight">
                Continuous intelligence
              </h2>
              <p className="font-serif text-sm leading-relaxed text-black/80">
                Panonica operates a persistent monitoring layer over 12 Croatian and EU data
                sources — FZOEU · NPOO · HEP grid queue · HROTE spot · DGU cadastral · OIEH
                press. Critical thresholds fire webhooks; a Friday digest summarizes everything
                into a 1-page PDF for the operator. One person's calendar cannot track 12
                regulatory bodies across 3 languages. Panonica does — continuously.
              </p>
              <div className="mt-4 grid grid-cols-4 gap-3 border-t border-black/10 pt-4">
                <InlineStat k="Sources monitored" v="12" />
                <InlineStat k="Poll cadence" v="15 min" />
                <InlineStat k="Languages" v="HR · EN · DE" />
                <InlineStat k="Alerts this week" v="3" />
              </div>
              <div className="mt-5 border-t border-black/10 pt-4">
                <div className="mb-1 font-mono text-[9px] uppercase tracking-[0.24em] text-black/50">
                  risk factors
                </div>
                <ul className="space-y-1 font-serif text-sm text-black/80">
                  <li>• UPU amendment pending (Q2 2026)</li>
                  <li>• Grid queue #14 · est. connection Q3 2027</li>
                  <li>• Net-billing post-2026 modelled in base case</li>
                  <li>• Land use reclassification risk · low (agri-preserving config)</li>
                </ul>
              </div>
            </div>
          </motion.article>
        </div>
      </div>

      {/* RIGHT — summary sidebar */}
      <aside className="w-[260px] shrink-0 self-start rounded-lg border border-border bg-surface/50 p-5">
        <div className="mb-3 font-mono text-[10px] uppercase tracking-[0.22em] text-text-muted">
          summary
        </div>
        <dl className="flex flex-col gap-2.5 font-mono text-[11px]">
          <SummaryKV k="Analyzed by" v="panonica_" />
          <SummaryKV k="Date" v="2026-04-18" />
          <SummaryKV k="Land area" v="80.3 ha" tone="pulse" />
          <SummaryKV k="Proposed" v="Agrivoltaic + sheep" />
          <SummaryKV k="Capacity" v="30 MW" tone="pulse" />
          <SummaryKV k="CAPEX" v="€21.0M" />
          <SummaryKV k="Payback" v="7.4 years" tone="pulse" />
          <SummaryKV k="Funding stack" v="€15.8M (75%)" tone="sun" />
          <SummaryKV k="Net CAPEX" v="€5.3M" tone="sun" />
          <SummaryKV k="NPV (25 yr)" v="€30.4M" />
          <SummaryKV k="IRR" v="11.4%" />
          <SummaryKV k="Exit EV y10" v="€30.4M" tone="sun" />
          <SummaryKV k="Equity MoM" v="7.8×" tone="sun" />
        </dl>
        <div className="mt-5 border-t border-border pt-4">
          <div className="font-mono text-[10px] uppercase tracking-[0.22em] text-text-muted">
            sources monitored
          </div>
          <div className="font-display text-lg tracking-tech-tight text-signal">12 · LIVE</div>
          <ul className="mt-3 flex flex-col gap-1 font-mono text-[10px] leading-relaxed text-text-secondary">
            <li>• FZOEU · NPOO · HBOR</li>
            <li>• HEP grid queue</li>
            <li>• HROTE spot · DGU cadastral</li>
            <li>• OIEH / Solarna Hrvatska press</li>
          </ul>
        </div>
        <div className="mt-5 border-t border-border pt-4">
          <div className="font-mono text-[10px] uppercase tracking-[0.22em] text-text-muted">
            confidence
          </div>
          <div className="font-display text-lg tracking-tech-tight text-agri">HIGH</div>
        </div>
      </aside>

      {/* TOAST */}
      <AnimatePresence>
        {toast && (
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 12 }}
            className="pointer-events-none absolute bottom-10 left-1/2 -translate-x-1/2 rounded-md border border-agri/30 bg-agri/15 px-4 py-2 font-mono text-[11px] uppercase tracking-[0.22em] text-agri backdrop-blur"
          >
            <Check className="inline h-3 w-3 mr-2" strokeWidth={2.5} />
            {toast}
          </motion.div>
        )}
      </AnimatePresence>
    </section>
  );
}

/* --------------------------------- sub ------------------------------------ */

function FieldDark({ label, value, tone }: { label: string; value: string; tone?: 'pulse' }) {
  return (
    <div>
      <div className="font-mono text-[9px] uppercase tracking-[0.24em] text-black/50">
        {label}
      </div>
      <div
        className={cn(
          'font-mono text-sm',
          tone === 'pulse' ? 'text-[#7C5CFF]' : 'text-black',
        )}
      >
        {value}
      </div>
    </div>
  );
}

function BigStat({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <div className="font-mono text-[9px] uppercase tracking-[0.24em] text-black/50">
        {label}
      </div>
      <div className="font-display text-2xl tracking-tech-tight">{value}</div>
    </div>
  );
}

function InlineStat({ k, v }: { k: string; v: string }) {
  return (
    <div className="flex flex-col gap-0.5">
      <span className="font-mono text-[8px] uppercase tracking-[0.22em] text-black/50">
        {k}
      </span>
      <span className="font-display text-sm tracking-tech-tight text-black">{v}</span>
    </div>
  );
}

function SummaryKV({
  k,
  v,
  tone,
}: {
  k: string;
  v: string;
  tone?: 'pulse' | 'sun';
}) {
  return (
    <div className="flex items-baseline justify-between border-b border-border/60 py-1">
      <dt className="text-[9px] uppercase tracking-[0.2em] text-text-muted">{k}</dt>
      <dd
        className={cn(
          'text-[11px] tabular-nums',
          tone === 'pulse' && 'text-pulse',
          tone === 'sun' && 'text-sun',
          !tone && 'text-text-primary',
        )}
      >
        {v}
      </dd>
    </div>
  );
}

function QrBlock() {
  // Stylized QR — 12×12 grid of deterministic cells with fake alignment corners
  const cells = Array.from({ length: 144 }, (_, i) => ((i * 37 + (i % 11) * 13) % 7) < 3);
  return (
    <div className="relative grid grid-cols-12 gap-[1px] rounded-sm bg-white p-1.5 shadow-[inset_0_0_0_1px_rgb(0,0,0,0.12)]">
      {cells.map((on, i) => {
        // Force corner "finder patterns" for QR feel
        const row = Math.floor(i / 12);
        const col = i % 12;
        const inCorner =
          (row < 3 && col < 3) ||
          (row < 3 && col > 8) ||
          (row > 8 && col < 3);
        const isOuterEdge =
          inCorner &&
          (row === 0 || row === 2 || row === 8 || row === 10 ||
            col === 0 || col === 2 || col === 8 || col === 10);
        const on2 = inCorner ? isOuterEdge || (row === 1 && col === 1) || (row === 1 && col === 9) || (row === 9 && col === 1) : on;
        return (
          <div
            key={i}
            className={cn('h-[4px] w-[4px]', on2 ? 'bg-black' : 'bg-white')}
          />
        );
      })}
    </div>
  );
}
